config/routes.rb
Rails.application.routes.draw do
  get 'carts/show'
  post 'places/:place_id/:dish_id/add' => 'line_dishes#create', as: 'add_dish'

  ActiveAdmin.routes(self)
  root 'places#index'
  devise_for :users
  resources :places, only: [:index, :show]
end

app/models/adapters/only_admins.rb
class Adapters::OnlyAdmins < ActiveAdmin::AuthorizationAdapter

  def authorized?(action, subject = nil)
    user.admin?
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/cart.rb
class Cart < ApplicationRecord

  has_many :line_dishes, dependent: :destroy
  has_many :dishes, through: :line_dishes




  def sub_total
    sum = 0

    self.line_dishes.each do |line_dish|
      if line_dish.dish.place.id == self.place_id
        sum+= line_dish.total_price
      end
    end
    return sum
  end
end

app/models/dish.rb
class Dish < ApplicationRecord
  validates :price, presence: true,
            numericality: {greater_than_or_equal_to: 0}
  has_one_attached :image
  validates :image,
        file_content_type: { allow: ['image/jpeg', 'image/gif', 'image/png'] }

  has_many :line_dishes

  belongs_to :place
end

app/models/line_dish.rb
class LineDish < ApplicationRecord
  belongs_to :dish
  belongs_to :cart

  def total_price
    self.quantity * self.dish.price
  end

end

app/models/place.rb
class Place < ApplicationRecord
  has_one_attached :picture
  validates :picture,
    file_content_type: { allow: ['image/jpeg', 'image/gif', 'image/png'] }

  has_many :dishes, dependent: :destroy

  has_one :cart
end

app/models/user.rb
class User < ApplicationRecord
  has_many :carts, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :current_cart

  def access_denied(exception)
    flash[:danger] = exception.message
    redirect_to root_url
  end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:update, keys: [:name, :phone, :address])

  end

  def current_cart
    if session[:cart_id]
      cart = Cart.find_by(:id => session[:cart_id])
      if cart.present?
        @current_cart = cart
      else
        session[:cart_id] = nil
      end
    end

    if session[:cart_id] == nil
      @current_cart = Cart.create
      session[:cart_id] = @current_cart.id
    end
  end


end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_place
  def show
    @cart = @current_cart
    @cart.place_id = @place.id
    @cart.save
  end

  def destroy
    @cart = @current_cart
    @cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
  end
  private
  def set_place
    @place = Place.find(params[:place_id])
  end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
end

app/controllers/line_dishes_controller.rb
class LineDishesController < ApplicationController
  before_action :current_cart

  def create

    chosen_product = Dish.find(params[:dish_id])
    current_cart = @current_cart

    if current_cart.dishes.include?(chosen_product)
      @line_dish = current_cart.line_dishes.find_by(:dish_id => chosen_product)
      @line_dish.quantity += 1
    else
      @line_dish = LineDish.new
      @line_dish.cart = current_cart
      @line_dish.dish = chosen_product
    end


    @line_dish.save
    redirect_to place_path(Place.find(params[:place_id]).id)
  end


  def destroy
    

  end



end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :find_place, only: [:show]

  def index
    @places = Place.all
  end

  def show
  end

  private

  def find_place
    @place = Place.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/line_dishes_helper.rb
module LineDishesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/carts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col d-flex flex-column align-items-center">
      <h2>Cart show</h2>
      <ul>
          <% @cart.line_dishes.each do |line_item| %>
            <%if line_item.dish.place.id == @place.id %>
              <li>Item: <%= line_item.dish.name %>/
                Price: <%= number_to_currency(line_item.dish.price) %>/
                Quantity: <%= line_item.quantity %>/
                Total Price: <%= number_to_currency(line_item.total_price) if line_item.dish.place.id == @place.id %>
              </li>
            <% end %>
          <% end %>
      </ul>

      <h3>Sub total: <%= number_to_currency(@cart.sub_total)%></h3>

      <div class="">
        <%= link_to "Back", places_path, class: 'btn btn-primary mt-2' %>
      </div>
      </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EFood</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="">
      <%= render 'layouts/application/navbar' %>
    </div>
    <div class="">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application/_navbar.html.erb
<nav class="navbar fixed-top navbar navbar-expand-md">
    <div class="container">
        <button type="button" class="navbar-toggler collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          &#x2630;
        </button>



        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <div class="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <div class="dropdown show">
                <%= link_to current_user.name, edit_user_registration_path(current_user), class: 'btn dropdown-toggle', 'role' => "button", 'id' => "dropdownMenuLink", 'data-toggle' => "dropdown", 'aria-haspopup' => "true", 'aria-expanded' => "false" %>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                  <%= link_to 'Edit profile', edit_user_registration_path(current_user), class: 'dropdown-item' %>
                  <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
                </div>
              <div>
              <% else %>
                  <div class="nav-item">
                     <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
                  </div>
                  <div class="nav-item">
                     <%= link_to 'Log in', new_user_session_path, class: 'nav-link' %>
                  </div>
              <% end %>
            </div>
        </div>
    </div>
</nav>

app/views/places/index.html.erb
<h1 class="mt-4">All places</h1>


<table class="table table-striped">
  <tr>
    <th></th>
    <th>Name</th>
  </tr>

  <% @places.each do |place| %>
    <tr>
      <td>
        <% if place.picture.attached? %>
          <%= image_tag place.picture, size: 100 %>
        <% end %>
      </td>
      <td>
        <%= link_to place.name, place_path(place) %>
      </td>
    </tr>
  <% end %>
</table>

app/views/places/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-9">
      <h1><%= @place.name %></h1>
    </div>
    <div class="col-4">
      <% if @place.picture.attached? %>
        <%= image_tag @place.picture, size: 200 %>
      <% end %>
    </div>
    <div class="col-6">
      <%= @place.description %>
    </div>
    <div class="col-2">
      <%= link_to 'Cart', carts_show_path(place_id: @place.id) %>
    </div>
  </div>
  <br/>
  <h2>Dishes</h2>
  <div class="row">
  <% @place.dishes.each do |dish| %>
      <div class="col-3 border">
        <% if dish.image.attached? %>
          <%= image_tag dish.image, size: 100 %>
        <% end %>
        <%= dish.name %>
        <%= link_to 'Добавить в корзину', add_dish_path(@place.id, dish.id), method: :post %>
      </div>
  <% end %>
  </div>
  <%= link_to "Back", places_path, class: 'btn btn-primary mt-2' %>
</div>